// Generated by CoffeeScript 1.4.0
(function() {
  var cloudfiles, crypto, cs, dateformat, decStream, encryptionPassword, fs, gunzip, inp, out, sourceFile, zlib;

  cloudfiles = require('cloudfiles');

  fs = require('fs');

  dateformat = require('dateformat');

  crypto = require('crypto');

  zlib = require('zlib');

  cs = require('cipherstream');

  sourceFile = process.argv[2];

  encryptionPassword = process.env.SURESPOT_RACKSPACE_ENCRYPTION_PASSWORD;

  if (!((encryptionPassword != null) && (sourceFile != null))) {
    process.exit(1);
  }

  gunzip = zlib.createGunzip();

  inp = fs.createReadStream(sourceFile);

  out = fs.createWriteStream("decrypted");

  decStream = new cs.DecipherStream(encryptionPassword);

  inp.pipe(decStream).pipe(gunzip).pipe(out);

}).call(this);
