// Generated by CoffeeScript 1.4.0
(function() {
  var cloudfiles, crypto, cs, dateformat, decipher, decrypted, encryptionPassword, fs, infile, outfile, sourceFile, stream, zlib;

  cloudfiles = require('cloudfiles');

  fs = require('fs');

  dateformat = require('dateformat');

  crypto = require('crypto');

  zlib = require('zlib');

  cs = require('cipherstream');

  stream = require('readable-stream');

  sourceFile = process.argv[2];

  encryptionPassword = process.env.SURESPOT_RACKSPACE_ENCRYPTION_PASSWORD;

  if (!((encryptionPassword != null) && (sourceFile != null))) {
    process.exit(1);
  }

  infile = fs.readFileSync(sourceFile);

  decipher = crypto.createDecipher("aes256", encryptionPassword);

  decrypted = decipher.update(infile, 'binary', 'utf8');

  decrypted += decipher.final();

  outfile = "" + sourceFile + ".gz";

  fs.writeFileSync(outfile, decrypted);

}).call(this);
