// Generated by CoffeeScript 1.4.0
(function() {
  var cloudfiles, crypto, cs, dateformat, encStream, encryptionPassword, fs, gzip, inp, out, outfile, sourceFile, zlib;

  cloudfiles = require('cloudfiles');

  fs = require('fs');

  dateformat = require('dateformat');

  crypto = require('crypto');

  zlib = require('zlib');

  cs = require('cipherstream');

  sourceFile = process.argv[2];

  if (sourceFile == null) {
    process.exit(1);
  }

  outfile = "" + sourceFile + ".encrypted";

  encryptionPassword = "password";

  gzip = zlib.createGzip();

  inp = fs.createReadStream(sourceFile);

  out = fs.createWriteStream(outfile);

  encStream = new cs.CipherStream(encryptionPassword);

  inp.pipe(gzip).pipe(encStream).pipe(out);

  out.on('close', function() {
    var decStream, gunzip, id, out2;
    gunzip = zlib.createGunzip();
    id = fs.createReadStream(outfile);
    out2 = fs.createWriteStream("" + sourceFile + ".original");
    decStream = new cs.DecipherStream(encryptionPassword);
    return id.pipe(decStream).pipe(gunzip).pipe(out2);
  });

}).call(this);
