// Generated by CoffeeScript 1.4.0
(function() {
  var Mocha, fs, mocha;

  Mocha = require('mocha');

  fs = require('fs');

  mocha = new Mocha({
    reporter: 'spec',
    timeout: 999999
  });

  mocha.addFile('test/deleteIdentityTests.js');

  mocha.run();

}).call(this);
